"""Combine all gauntlet-validated rules into two species files.

    rules/validated*.jsonl  (+ rules/retired.jsonl)
        -> rules/bridging_rules.jsonl        (type == "bridging")
        -> rules/consolidation_rules.jsonl   (type == "consolidation")

One row per rule that PASSED its gauntlet round (rejected rows stay only in the
per-round files and the ledger). Rows keep their original fields verbatim, plus:

    gauntlet_round   1 for validated.jsonl, N for validatedN.jsonl
    source_file      the per-round file the row came from
    status           "validated", or "retired" when the id appears in
                     rules/retired.jsonl (retirement details joined under "retired")

Deterministic: rows sorted by (gauntlet_round, id); re-running is byte-identical.
Re-run after every gauntlet round (a future validated4.jsonl is picked up by the
glob) and after any retirement.

Also emits MeTTa renderings of both species:

    rules/bridging_rules.metta        the per-wave `mined_bridges_wave*.metta`
                                      exports combined verbatim (retired rules are
                                      already excluded by the wave exporters)
    rules/consolidation_rules.metta   one Implication atom per rule in the wave-
                                      exporter idiom — a syntax rendering of the
                                      species; production applies consolidation via
                                      the rewriter/packed views, never by loading
                                      this file beside the KB
"""
import glob
import json
import os
import re

RULES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rules")


def load(path):
    with open(path) as fh:
        return [json.loads(line) for line in fh if line.strip()]


def main():
    retired = {r["id"]: r for r in load(os.path.join(RULES, "retired.jsonl"))}
    out = {"bridging": [], "consolidation": []}
    seen = set()
    for path in sorted(glob.glob(os.path.join(RULES, "validated*.jsonl"))):
        name = os.path.basename(path)
        m = re.fullmatch(r"validated(\d*)\.jsonl", name)
        if not m:
            continue
        rnd = int(m.group(1) or "1")
        for row in load(path):
            if row.get("status") != "validated":
                continue
            rid = row["id"]
            if rid in seen:
                raise SystemExit(f"duplicate rule id across rounds: {rid}")
            seen.add(rid)
            row["gauntlet_round"] = rnd
            row["source_file"] = f"rules/{name}"
            if rid in retired:
                row["status"] = "retired"
                row["retired"] = {k: v for k, v in retired[rid].items() if k != "id"}
            species = row.get("type")
            if species not in out:
                raise SystemExit(f"unknown rule type {species!r} on {rid}")
            out[species].append(row)

    for species, rows in out.items():
        rows.sort(key=lambda r: (r["gauntlet_round"], r["id"]))
        path = os.path.join(RULES, f"{species}_rules.jsonl")
        with open(path, "w") as fh:
            for r in rows:
                fh.write(json.dumps(r, sort_keys=True) + "\n")
        live = sum(1 for r in rows if r["status"] == "validated")
        ret = len(rows) - live
        print(f"{path}: {len(rows)} rows ({live} validated, {ret} retired), "
              f"rounds {sorted({r['gauntlet_round'] for r in rows})}")

    write_bridging_metta()
    write_consolidation_metta(out["consolidation"])


def write_bridging_metta():
    """Combine the wave exports verbatim — they are the validated compiled form."""
    waves = sorted(glob.glob(os.path.join(RULES, "mined_bridges_wave*.metta")))
    path = os.path.join(RULES, "bridging_rules.metta")
    atoms = 0
    with open(path, "w") as fh:
        fh.write("; ===== FUSE-NF bridge serving file — ALL WAVES COMBINED =====\n")
        fh.write("; generated by mining/combine_rules.py; the per-wave\n")
        fh.write("; mined_bridges_wave*.metta exports concatenated verbatim\n")
        fh.write("; (audit-retired rules are already excluded by those exports).\n")
        fh.write("; NOTE: beside the bridging species proper, this includes the mutual\n")
        fh.write("; serving form of validated LEXICAL CONSOLIDATION rules (wave-exporter\n")
        fh.write("; convention, conf = min(0.9, 0.7 + 0.05*support)) — in the faithful\n")
        fh.write("; QA layout a lossless equivalence is served as a bidirectional bridge;\n")
        fh.write("; its one-directional rewrite form applies only in packed views.\n")
        fh.write("; Load beside seeded_rules.metta INSTEAD of the wave files,\n")
        fh.write("; never in addition to them (proof names would collide).\n")
        for wpath in waves:
            fh.write(f"\n; ===== from {os.path.basename(wpath)} =====\n")
            with open(wpath) as wf:
                body = wf.read()
            fh.write(body if body.endswith("\n") else body + "\n")
            atoms += sum(1 for line in body.splitlines() if line.startswith("("))
    print(f"{path}: {atoms} implication atoms from {len(waves)} wave files")


def side(clauses):
    return clauses[0] if len(clauses) == 1 else "(And " + " ".join(clauses) + ")"


def write_consolidation_metta(rows):
    """One Implication atom per rule, wave-exporter idiom, stored direction only."""
    path = os.path.join(RULES, "consolidation_rules.metta")
    atoms = 0
    with open(path, "w") as fh:
        fh.write("; ===== FUSE-NF consolidation rules (ALL GAUNTLET ROUNDS) =====\n")
        fh.write("; generated by mining/combine_rules.py from rules/consolidation_rules.jsonl.\n")
        fh.write("; SYNTAX RENDERING ONLY: production applies the consolidation species\n")
        fh.write("; through the rewriter (packed/consolidated views); this file is not\n")
        fh.write("; loaded beside the KB for QA. Subtree-collapse RHS heads (Mn*) are\n")
        fh.write("; pack vocabulary, meaningful only with the packed-view definitions.\n")
        fh.write("; TVs: strength 1.0 (lossless species), confidence = gauntlet confidence.\n")
        for r in rows:
            if r["status"] != "validated":
                fh.write(f"; {r['id']} EXCLUDED — status {r['status']}\n")
                continue
            assert r.get("direction") == "lhs->rhs", r["id"]
            name = f"consol_r{r['gauntlet_round']}_{r['id']}"
            fh.write(f"\n; {r['id']} — {r['kind']}, round {r['gauntlet_round']}, "
                     f"support {r.get('support')}\n")
            fh.write(f"(: {name} (Implication {side(r['lhs'])} {side(r['rhs'])}) "
                     f"(STV 1.0 {r['confidence']}))\n")
            atoms += 1
    print(f"{path}: {atoms} implication atoms")


if __name__ == "__main__":
    main()
