"""Combine gauntlet-validated CONSOLIDATION rules into the single-species ledger.

    rules/validated*.jsonl  (+ rules/retired.jsonl)
        -> rules/consolidation_rules.jsonl
        -> rules/consolidation_rules.metta   (syntax rendering)

#50 (owner 2026-09-01): consolidation is FUSE-NF's only rule species. Historical
"bridging"-typed rows in the per-round validated files are SKIPPED here (counted
in the summary line) — they, the last-generated rules/bridging_rules.*, and the
mined_bridges_wave*.metta exports stay on disk as batch-1 experimental records:
no longer deliverables, no longer regenerated (the bridge exporters are deleted;
git history has them).

One row per rule that PASSED its gauntlet round (rejected rows stay only in the
per-round files and the ledger). Rows keep their original fields verbatim, plus:

    gauntlet_round   1 for validated.jsonl, N for validatedN.jsonl
    source_file      the per-round file the row came from
    status           "validated", or "retired" when the id appears in
                     rules/retired.jsonl (retirement details joined under "retired")

Deterministic: rows sorted by (gauntlet_round, id); re-running is byte-identical.
Re-run after every gauntlet round (a future validated4.jsonl is picked up by the
glob) and after any retirement.

The .metta rendering is one Implication atom per validated rule in the stored
(canonical) direction — production applies the species through the rewriter
(consolidated views), and the query normalizer applies the SAME rules to queries
at submission time; the file is never loaded beside a KB.
"""
import glob
import json
import os
import re

RULES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rules")


def load(path):
    with open(path) as fh:
        return [json.loads(line) for line in fh if line.strip()]


def main():
    retired = {r["id"]: r for r in load(os.path.join(RULES, "retired.jsonl"))}
    rows, seen = [], set()
    historical_bridging = 0
    for path in sorted(glob.glob(os.path.join(RULES, "validated*.jsonl"))):
        name = os.path.basename(path)
        m = re.fullmatch(r"validated(\d*)\.jsonl", name)
        if not m:
            continue
        rnd = int(m.group(1) or "1")
        for row in load(path):
            if row.get("status") != "validated":
                continue
            rid = row["id"]
            if rid in seen:
                raise SystemExit(f"duplicate rule id across rounds: {rid}")
            seen.add(rid)
            if row.get("type") == "bridging":   # pre-#50 history: record, not deliverable
                historical_bridging += 1
                continue
            if row.get("type") != "consolidation":
                raise SystemExit(f"unknown rule type {row.get('type')!r} on {rid}")
            row["gauntlet_round"] = rnd
            row["source_file"] = f"rules/{name}"
            if rid in retired:
                row["status"] = "retired"
                row["retired"] = {k: v for k, v in retired[rid].items() if k != "id"}
            rows.append(row)

    rows.sort(key=lambda r: (r["gauntlet_round"], r["id"]))
    path = os.path.join(RULES, "consolidation_rules.jsonl")
    with open(path, "w") as fh:
        for r in rows:
            fh.write(json.dumps(r, sort_keys=True) + "\n")
    live = sum(1 for r in rows if r["status"] == "validated")
    print(f"{path}: {len(rows)} rows ({live} validated, {len(rows) - live} retired), "
          f"rounds {sorted({r['gauntlet_round'] for r in rows})}; "
          f"{historical_bridging} historical bridging-species rows skipped (#50)")
    write_consolidation_metta(rows)


def side(clauses):
    return clauses[0] if len(clauses) == 1 else "(And " + " ".join(clauses) + ")"


def write_consolidation_metta(rows):
    """One Implication atom per rule, stored (canonical) direction only."""
    path = os.path.join(RULES, "consolidation_rules.metta")
    atoms = 0
    with open(path, "w") as fh:
        fh.write("; ===== FUSE-NF consolidation rules (ALL GAUNTLET ROUNDS) =====\n")
        fh.write("; generated by mining/combine_rules.py from rules/validated*.jsonl.\n")
        fh.write("; SYNTAX RENDERING ONLY: production applies the species through the\n")
        fh.write("; rewriter (consolidated views), and the query normalizer applies the\n")
        fh.write("; same rules to queries at submission time (#50); this file is never\n")
        fh.write("; loaded beside the KB. Subtree-collapse RHS heads (Mn*) are pack\n")
        fh.write("; vocabulary; their decode direction is the same rule read backwards.\n")
        fh.write("; TVs: strength 1.0, confidence = gauntlet confidence. Fuzz (2026-09-02) is a RULE\n")
        fh.write("; annotation, not an STV: fuzzy rules carry their judge loss category in the\n")
        fh.write("; comment. modifier-prune rules render as (Prune <lhs>) — rendering only; the\n")
        fh.write("; rewriter deletes the matched atoms.\n")
        for r in rows:
            if r["status"] != "validated":
                fh.write(f"; {r['id']} EXCLUDED — status {r['status']}\n")
                continue
            assert r.get("direction") == "lhs->rhs", r["id"]
            name = f"consol_r{r['gauntlet_round']}_{r['id']}"
            g = r.get("gauntlet") or {}
            fuzz = f", fuzzy (loss: {g.get('probe_loss')})" if g.get("fuzzy") else ""
            fh.write(f"\n; {r['id']} — {r['kind']}, round {r['gauntlet_round']}, "
                     f"support {r.get('support')}{fuzz}\n")
            if r["rhs"]:
                fh.write(f"(: {name} (Implication {side(r['lhs'])} {side(r['rhs'])}) "
                         f"(STV 1.0 {r['confidence']}))\n")
            else:   # modifier-prune
                fh.write(f"(: {name} (Prune {side(r['lhs'])}) (STV 1.0 {r['confidence']}))\n")
            atoms += 1
    print(f"{path}: {atoms} implication atoms")


if __name__ == "__main__":
    main()
