"""FUSE-NF — the rule ledger, readable: every candidate across all gauntlet rounds.

Joins the three layers that already exist on disk — proposals
(``rules/candidates*.jsonl`` + ``.mech`` gate results), judge evidence
(``rules/probes*/votes_*.jsonl``), and verdicts (``rules/validated*.jsonl``) — into one
markdown ledger, one block per rule: LHS ↔ RHS, support, mechanical gates, every judge's
vote verbatim, final routing with confidence and note. Read-only; a VIEW in the
canon_view.py sense — nothing downstream may read it.

Usage (from fusenf/harness):
  python ledger_view.py [--out ../eval/rule_ledger.md]
"""

from __future__ import annotations

import argparse
import collections
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
FUSENF = os.path.dirname(HERE)
R = os.path.join(FUSENF, "rules")

ROUNDS = (
    ("round 1 — wave-1 candidates (2026-08-14)", "candidates.jsonl", "probes", "validated.jsonl"),
    ("round 2 — wave-2 meta-nodes + AE (2026-08-14)", "candidates2.jsonl", "probes2", "validated2.jsonl"),
    ("round 3 — loop-2 singletons (2026-08-17)", "candidates3.jsonl", "probes3", "validated3.jsonl"),
)

VOTE_SKIP = ("rule_id",)          # everything else a vote carries is shown verbatim
MECH_FIELDS = ("consensus_votes", "tierA_control_merges", "tierA_newly_identical",
               "frozen_head_rewrite", "seeded_collision", "symbol_pair_ok",
               "marginal_strict", "bijective", "coherence")


def load_jsonl(path):
    if not os.path.exists(path):
        return []
    return [json.loads(l) for l in open(path, encoding="utf-8") if l.strip()]


def atoms(side):
    return side if isinstance(side, list) else [str(side)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(FUSENF, "eval", "rule_ledger.md"))
    args = ap.parse_args()

    L = ["# FUSE-NF rule ledger — every candidate, all gauntlet rounds",
         "",
         "Generated by `harness/ledger_view.py` from `rules/candidates*`, `rules/probes*/votes_*`,",
         "`rules/validated*`. One block per rule: proposal, mechanical gates, judge votes verbatim,",
         "final routing. Compiled implications live in `rules/mined_bridges_wave{1,2,3}.metta`.", ""]

    grand = collections.Counter()
    for title, cand_f, probes_d, val_f in ROUNDS:
        cands = {r["id"]: r for r in load_jsonl(os.path.join(R, cand_f))}
        mech = {r["id"]: r for r in load_jsonl(os.path.join(R, cand_f + ".mech"))}
        final = {r["id"]: r for r in load_jsonl(os.path.join(R, val_f))}
        votes = collections.defaultdict(list)
        for vf in sorted(glob.glob(os.path.join(R, probes_d, "votes_*.jsonl"))):
            judge = os.path.basename(vf)[len("votes_"):-len(".jsonl")]
            for v in load_jsonl(vf):
                votes[v.get("rule_id")].append((judge, v))

        ids = sorted(set(cands) | set(final),
                     key=lambda i: (final.get(i, {}).get("status", "~"),
                                    final.get(i, {}).get("type", "~"), i))
        by = collections.Counter(
            f"{final[i].get('status','?')}/{final[i].get('type','-')}" if i in final
            else "no-verdict" for i in ids)
        grand.update(by)
        L.append(f"## {title} — {len(ids)} candidates")
        L.append("  " + ", ".join(f"{k}: {n}" for k, n in sorted(by.items())))
        L.append("")

        for rid in ids:
            c = cands.get(rid) or final.get(rid) or {}
            f = final.get(rid)
            head = f"### {rid} — {c.get('kind', '?')}"
            if f:
                head += f" — **{f.get('status', '?')}/{f.get('type', '-')}** conf {f.get('confidence', '?')}"
            else:
                head += " — (no verdict recorded)"
            L.append(head)
            lhs, rhs = atoms(c.get("lhs", [])), atoms(c.get("rhs", []))
            L.append("```")
            for a in lhs:
                L.append(f"LHS  {a}")
            for a in rhs:
                L.append(f"RHS  {a}")
            L.append("```")
            bits = [f"support {c.get('support', '?')}", f"direction {c.get('direction', '-')}"]
            prov = c.get("provenance") or {}
            if isinstance(prov, dict) and prov.get("method"):
                bits.append(f"method {prov['method']}")
            ex = prov.get("examples") if isinstance(prov, dict) else None
            if ex:
                bits.append(f"examples {len(ex)} ({', '.join(map(str, ex[:3]))}{'…' if len(ex) > 3 else ''})")
            L.append("- " + " · ".join(bits))
            m = mech.get(rid)
            if m:
                shown = [f"{k}={m[k]}" for k in MECH_FIELDS if k in m]
                extra = [k for k in m if k not in MECH_FIELDS and k not in c and k != "id"]
                shown += [f"{k}={m[k]}" for k in sorted(extra)]
                L.append("- mech: " + (", ".join(shown) if shown else "(no gate fields)"))
            for judge, v in sorted(votes.get(rid, [])):
                fields = ", ".join(f"{k}={json.dumps(v[k], ensure_ascii=False)}"
                                   for k in v if k not in VOTE_SKIP and k != "note")
                note = v.get("note", "")
                L.append(f"- vote `{judge}`: {fields}" + (f" — {note}" if note else ""))
            if f:
                g = f.get("gauntlet")
                if g:
                    L.append(f"- routing: {json.dumps(g, ensure_ascii=False)[:400]}")
            L.append("")

    L.insert(5, "**Grand totals**: " + ", ".join(f"{k}: {n}" for k, n in sorted(grand.items())) + "\n")
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"-> {args.out}")


if __name__ == "__main__":
    main()
